const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const navItems=[
 ['dashboard','▦','Dashboard','Visão geral da operação DS'],['recebimento','▥','Recebimento DS','Entrada e conferência de carga'],['triagem','⌗','Triagem','Separação e preparação'],['despacho','⇄','Despacho','Distribuição para motoristas'],['rota','⌁','Em rota','Acompanhamento das saídas'],['entregues','✓','Entregues','Baixas e comprovantes'],['ocorrencias','!','Ocorrências','Insucessos e tratativas'],['devolucoes','↩','Devoluções','Retorno de volumes'],
 ['sla','◷','SLA','Período, motorista, base e localidade'],['motoristas','♙','Motoristas','Cadastro e dados bancários'],['bases','⌂','Bases','4 bases operacionais e expansão'],['despesas','$','Despesas','Gestão de despesas'],['usuarios','⚿','Usuários / Admin','Perfis e permissões'],['ia','✦','IA','Análises inteligentes'],['relatorios','▤','Relatórios','Indicadores e produtividade']
];
const now=()=>new Date().toLocaleString('pt-BR');
const todayISO=()=>new Date().toISOString().slice(0,10);
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

const demo={
 bases:[
  {id:'b1',nome:'Base 1',localidade:'Salvador',status:'Ativa'},
  {id:'b2',nome:'Base 2',localidade:'Candeias',status:'Ativa'},
  {id:'b3',nome:'Base 3',localidade:'Simões Filho',status:'Ativa'},
  {id:'b4',nome:'Base 4',localidade:'Lauro de Freitas',status:'Ativa'}
 ],
 drivers:[
  {id:'d1',nome:'Rafael Santos',telefone:'71999990011',nascimento:'1991-08-25',rota:'Salvador Centro',valorPacote:3.5,base:'Base 1',banco:'',agencia:'',conta:'',pix:'',status:'Ativo',obs:''},
  {id:'d2',nome:'Diego Lima',telefone:'71999990012',nascimento:'1988-11-10',rota:'Candeias',valorPacote:3.2,base:'Base 2',banco:'',agencia:'',conta:'',pix:'',status:'Ativo',obs:''},
  {id:'d3',nome:'Lucas Rocha',telefone:'71999990013',nascimento:'1994-03-18',rota:'Simões Filho',valorPacote:3.4,base:'Base 3',banco:'',agencia:'',conta:'',pix:'',status:'Ativo',obs:''},
  {id:'d4',nome:'André Costa',telefone:'71999990014',nascimento:'1990-06-02',rota:'Lauro de Freitas',valorPacote:3.3,base:'Base 4',banco:'',agencia:'',conta:'',pix:'',status:'Ativo',obs:''}
 ],
 orders:[
  {waybill:'WB260824001',referencia:'PED-90831',cliente:'Loja Alpha',destinatario:'Carlos Silva',telefone:'71999990001',endereco:'Rua A, 120',cidade:'Salvador',localidade:'Centro',base:'Base 1',prazo:'2026-08-25',status:'Em rota',volumes:1,entregador:'Rafael Santos',ultimo:'Saiu para entrega',atualizacao:'25/08/2026 08:42',ocorrencia:''},
  {waybill:'WB260824002',referencia:'PED-90832',cliente:'Marketplace Beta',destinatario:'Ana Souza',telefone:'71999990002',endereco:'Av. Central, 45',cidade:'Candeias',localidade:'Centro',base:'Base 2',prazo:'2026-08-26',status:'Recebido no DS',volumes:2,entregador:'',ultimo:'Recebido no DS',atualizacao:'25/08/2026 07:10',ocorrencia:''},
  {waybill:'WB260824003',referencia:'PED-90833',cliente:'Loja Alpha',destinatario:'João Santos',telefone:'71999990003',endereco:'Rua das Flores, 9',cidade:'Simões Filho',localidade:'CIA',base:'Base 3',prazo:'2026-08-25',status:'Entregue',volumes:1,entregador:'Lucas Rocha',ultimo:'Entregue',atualizacao:'25/08/2026 09:05',ocorrencia:''},
  {waybill:'WB260824004',referencia:'PED-90834',cliente:'Seller Gamma',destinatario:'Marcos Lima',telefone:'71999990004',endereco:'Rua B, 77',cidade:'Salvador',localidade:'Itapuã',base:'Base 1',prazo:'2026-08-24',status:'Ocorrência',volumes:1,entregador:'Diego Lima',ultimo:'Tentativa sem sucesso',atualizacao:'25/08/2026 08:18',ocorrencia:'Destinatário ausente'},
  {waybill:'WB260824005',referencia:'PED-90835',cliente:'Marketplace Beta',destinatario:'Paula Reis',telefone:'71999990005',endereco:'Praça Norte, 20',cidade:'Lauro de Freitas',localidade:'Centro',base:'Base 4',prazo:'2026-08-26',status:'Triagem',volumes:3,entregador:'',ultimo:'Em triagem',atualizacao:'25/08/2026 08:05',ocorrencia:''}
 ],
 expenses:[
  {id:'e1',descricao:'Combustível apoio operacional',valor:280,data:'2026-08-24',pagamento:'PIX',categoria:'Combustível',base:'Base 1',responsavel:'Operação',obs:''}
 ],
 users:[
  {id:'u1',nome:'Administrador',email:'admin@empresa.com',perfil:'Super Admin',base:'Todas',status:'Ativo'}
 ]
};
const KEY='last-mile-ds-v5';
function migrate(){
 let v5=JSON.parse(localStorage.getItem(KEY)||'null'); if(v5)return v5;
 let old=JSON.parse(localStorage.getItem('last-mile-ds-v4')||'null');
 let s=structuredClone(demo);
 if(old?.orders?.length){s.orders=old.orders.map((o,i)=>({...o,base:o.base||`Base ${(i%4)+1}`,localidade:o.localidade||o.cidade||''}));}
 return s;
}
let state=migrate();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)); save();

function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function badge(s){let c=s==='Entregue'?'green':s==='Ocorrência'||s==='Devolução'?'red':s==='Em rota'?'blue':s==='Triagem'||s==='Despachado'?'orange':'';return `<span class="badge ${c}">${esc(s)}</span>`}
function slaText(o){const d=new Date(o.prazo+'T23:59:59');if(o.status==='Entregue')return'Concluído';const t=new Date();return d<t?'Atrasado':d.toDateString()===t.toDateString()?'Vence hoje':'No prazo'}
function sla(o){let s=slaText(o);return `<span class="sla ${s==='Atrasado'?'late':s==='Vence hoje'?'warn':'ok'}">${s}</span>`}
function kpi(t,v,s,c=''){return `<div class="card kpi ${c}"><span>${t}</span><strong>${v}</strong><small>${s}</small></div>`}
function baseOptions(includeAll=false){return `${includeAll?'<option value="">Todas as bases</option>':''}${state.bases.filter(b=>b.status==='Ativa').map(b=>`<option value="${esc(b.nome)}">${esc(b.nome)}</option>`).join('')}`}
function driverOptions(includeAll=false){return `${includeAll?'<option value="">Todos os motoristas</option>':''}${state.drivers.filter(d=>d.status==='Ativo').map(d=>`<option value="${esc(d.nome)}">${esc(d.nome)}</option>`).join('')}`}
function fillDialogOptions(){['#wbBase','#driverBase','#expenseBase'].forEach(sel=>{let x=$(sel);if(x)x.innerHTML=baseOptions(false)});let u=$('#userBase');if(u)u.innerHTML='<option value="Todas">Todas as bases</option>'+state.bases.map(b=>`<option>${esc(b.nome)}</option>`).join('')}
function table(rows,actions=true){return `<div class="table-wrap"><table class="table"><thead><tr><th>Waybill</th><th>Referência</th><th>Cliente</th><th>Destinatário</th><th>Base</th><th>Localidade</th><th>Motorista</th><th>Prazo</th><th>SLA</th><th>Status</th><th>Última atualização</th>${actions?'<th>Ações</th>':''}</tr></thead><tbody>${rows.map(o=>`<tr><td><strong>${esc(o.waybill)}</strong></td><td>${esc(o.referencia||'-')}</td><td>${esc(o.cliente)}</td><td>${esc(o.destinatario)}</td><td>${esc(o.base||'-')}</td><td>${esc(o.localidade||o.cidade||'-')}</td><td>${esc(o.entregador||'-')}</td><td>${new Date(o.prazo+'T12:00').toLocaleDateString('pt-BR')}</td><td>${sla(o)}</td><td>${badge(o.status)}</td><td><small>${esc(o.ultimo)}<br>${esc(o.atualizacao)}</small></td>${actions?`<td><button class="row-btn" onclick="openActions('${esc(o.waybill)}')">•••</button></td>`:''}</tr>`).join('')||'<tr><td colspan="12" class="empty">Nenhum volume nesta etapa.</td></tr>'}</tbody></table></div>`}

function dashboard(){
 let n=state.orders.length,e=state.orders.filter(x=>x.status==='Entregue').length,r=state.orders.filter(x=>x.status==='Em rota').length,oc=state.orders.filter(x=>x.status==='Ocorrência').length,late=state.orders.filter(x=>slaText(x)==='Atrasado').length;
 let birthdays=state.drivers.filter(isBirthdayToday);
 return `<div class="grid kpis">${kpi('Carga total',n,'Waybills na operação')}${kpi('Em rota',r,'Saídas ativas')}${kpi('Entregues',e,'Baixas concluídas')}${kpi('Ocorrências',oc,'Requer tratativa','warn')}${kpi('SLA vencido',late,'Volumes atrasados','danger')}</div>
 <div class="grid section-grid"><div class="card"><h3>Fluxo operacional</h3><div class="flow">${['Recebido no DS','Triagem','Despachado','Em rota','Entregue'].map(s=>`<div><b>${state.orders.filter(x=>x.status===s).length}</b><span>${s}</span></div>`).join('')}</div></div>
 <div class="card"><h3>Atenção operacional</h3><div class="mini-list">${state.orders.filter(x=>x.status==='Ocorrência'||slaText(x)==='Atrasado').map(x=>`<div class="mini-item"><div><strong>${esc(x.waybill)}</strong><span>${esc(x.ocorrencia||slaText(x))} • ${esc(x.base)}</span></div>${badge(x.status)}</div>`).join('')||'<div class="empty">Sem pendências críticas.</div>'}</div></div></div>
 <div class="card" style="margin-top:18px"><div class="toolbar"><div><h3>Aniversariantes de hoje</h3><p class="muted">A data de nascimento do cadastro alimenta esta automação.</p></div></div>${birthdays.length?birthdays.map(d=>`<div class="mini-item"><div><strong>${esc(d.nome)}</strong><span>${esc(d.telefone)} • ${esc(d.base)}</span></div><button class="ghost-btn" onclick="birthdayMessage('${d.id}')">Preparar mensagem</button></div>`).join(''):'<div class="empty">Nenhum motorista aniversariando hoje.</div>'}</div>`
}
function listPage(status,help){let rows=status==='Recebimento'?state.orders.filter(x=>x.status==='Recebido no DS'):status==='Triagem'?state.orders.filter(x=>x.status==='Triagem'):status==='Despacho'?state.orders.filter(x=>['Despachado','Recebido no DS','Triagem'].includes(x.status)):status==='Em rota'?state.orders.filter(x=>x.status==='Em rota'):status==='Entregue'?state.orders.filter(x=>x.status==='Entregue'):status==='Ocorrência'?state.orders.filter(x=>x.status==='Ocorrência'):state.orders.filter(x=>x.status==='Devolução');return `<div class="card"><div class="toolbar"><input class="search" id="search" placeholder="Buscar Waybill, referência, cliente, base ou motorista"><span class="toolbar-note">${help}</span></div>${table(rows)}</div>`}

function slaPage(){
 const today=todayISO(); const start=new Date();start.setDate(start.getDate()-7);const startISO=start.toISOString().slice(0,10);
 return `<div class="card"><div class="filter-grid"><label>Data inicial<input id="slaStart" type="date" value="${startISO}"></label><label>Data final<input id="slaEnd" type="date" value="${today}"></label><label>Motorista<select id="slaDriver">${driverOptions(true)}</select></label><label>Base<select id="slaBase">${baseOptions(true)}</select></label><label>Localidade<input id="slaLocal" placeholder="Digite a localidade"></label><div class="filter-actions"><button class="primary-btn" id="slaApply">Filtrar</button><button class="ghost-btn" id="slaClear">Limpar</button></div></div></div><div id="slaResult" style="margin-top:18px"></div>`
}
function renderSlaResults(){
 let a=$('#slaStart')?.value,b=$('#slaEnd')?.value,driver=$('#slaDriver')?.value||'',base=$('#slaBase')?.value||'',local=($('#slaLocal')?.value||'').toLowerCase();
 let rows=state.orders.filter(o=>(!a||o.prazo>=a)&&(!b||o.prazo<=b)&&(!driver||o.entregador===driver)&&(!base||o.base===base)&&(!local||String(o.localidade||o.cidade).toLowerCase().includes(local)));
 let total=rows.length, delivered=rows.filter(o=>o.status==='Entregue').length, late=rows.filter(o=>slaText(o)==='Atrasado').length, occ=rows.filter(o=>o.status==='Ocorrência').length, onTime=rows.filter(o=>slaText(o)!=='Atrasado').length;
 let pct=total?Math.round(onTime/total*100):0;
 $('#slaResult').innerHTML=`<div class="grid kpis">${kpi('SLA',pct+'%','Dentro do prazo')}${kpi('Pacotes',total,'No filtro selecionado')}${kpi('Entregues',delivered,'Baixas concluídas')}${kpi('Atrasados',late,'SLA vencido','danger')}${kpi('Ocorrências',occ,'Insucessos','warn')}</div><div class="card" style="margin-top:18px"><h3>Detalhamento do período</h3>${table(rows,false)}</div>`;
}

function driversPage(){
 return `<div class="card"><div class="toolbar"><div><h3>Cadastro de motoristas</h3><p class="muted">Nascimento, rota, valor por pacote, banco, PIX e base atendida.</p></div><button class="primary-btn" id="addDriver">+ Novo motorista</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Nome</th><th>Telefone</th><th>Nascimento</th><th>Rota desejada</th><th>Valor/pacote</th><th>Base</th><th>Banco</th><th>PIX</th><th>Status</th><th>Ações</th></tr></thead><tbody>${state.drivers.map(d=>`<tr><td><strong>${esc(d.nome)}</strong></td><td>${esc(d.telefone)}</td><td>${d.nascimento?new Date(d.nascimento+'T12:00').toLocaleDateString('pt-BR'):'-'}</td><td>${esc(d.rota||'-')}</td><td>${money(d.valorPacote)}</td><td>${esc(d.base||'-')}</td><td>${esc(d.banco||'-')}</td><td>${esc(d.pix||'-')}</td><td>${badge(d.status)}</td><td><button class="row-btn" onclick="editDriver('${d.id}')">Editar</button></td></tr>`).join('')}</tbody></table></div></div>`
}
function basesPage(){return `<div class="card"><div class="toolbar"><div><h3>Bases operacionais</h3><p class="muted">O sistema começa com 4 bases, mas permite cadastrar novas.</p></div><button class="primary-btn" id="addBase">+ Nova base</button></div><div class="grid base-cards">${state.bases.map(b=>`<div class="subcard"><div class="toolbar"><div><h3>${esc(b.nome)}</h3><p>${esc(b.localidade)}</p></div>${badge(b.status)}</div><button class="ghost-btn" onclick="editBase('${b.id}')">Editar</button></div>`).join('')}</div></div>`}
function expensesPage(){let total=state.expenses.reduce((a,b)=>a+Number(b.valor||0),0);return `<div class="grid kpis">${kpi('Despesas registradas',state.expenses.length,'Lançamentos')}${kpi('Total',money(total),'Valor acumulado')}${kpi('Este mês',money(state.expenses.filter(e=>e.data.slice(0,7)===todayISO().slice(0,7)).reduce((a,b)=>a+Number(b.valor||0),0)),'Competência atual')}</div><div class="card" style="margin-top:18px"><div class="toolbar"><div><h3>Gestão de despesas</h3><p class="muted">Descrição, valor, data, forma de pagamento, categoria e base.</p></div><button class="primary-btn" id="addExpense">+ Nova despesa</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Descrição</th><th>Categoria</th><th>Base</th><th>Pagamento</th><th>Responsável</th><th>Valor</th><th></th></tr></thead><tbody>${state.expenses.map(e=>`<tr><td>${new Date(e.data+'T12:00').toLocaleDateString('pt-BR')}</td><td>${esc(e.descricao)}</td><td>${esc(e.categoria)}</td><td>${esc(e.base)}</td><td>${esc(e.pagamento)}</td><td>${esc(e.responsavel||'-')}</td><td><strong>${money(e.valor)}</strong></td><td><button class="row-btn" onclick="deleteExpense('${e.id}')">Excluir</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">Nenhuma despesa cadastrada.</td></tr>'}</tbody></table></div></div>`}
function usersPage(){return `<div class="card"><div class="toolbar"><div><h3>Usuários administrativos</h3><p class="muted">Perfis de acesso para donos, operação, financeiro e consulta.</p></div><button class="primary-btn" id="addUser">+ Novo usuário</button></div><div class="info-box"><strong>Importante:</strong> GitHub Pages é apenas frontend. Para login seguro dos donos, senha, recuperação de acesso e permissões reais, a próxima etapa precisa conectar um serviço de autenticação/backend.</div><div class="table-wrap"><table class="table"><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Base</th><th>Status</th></tr></thead><tbody>${state.users.map(u=>`<tr><td>${esc(u.nome)}</td><td>${esc(u.email)}</td><td>${esc(u.perfil)}</td><td>${esc(u.base)}</td><td>${badge(u.status)}</td></tr>`).join('')}</tbody></table></div></div>`}
function iaPage(){return `<div class="grid section-grid"><div class="card"><h3>Assistente operacional</h3><p class="muted">Nesta V5 o assistente analisa os dados locais. Depois podemos conectar uma IA real pelo backend, sem expor chave de API.</p><div class="ai-prompts"><button class="ghost-btn ai-q" data-q="sla">Analisar SLA</button><button class="ghost-btn ai-q" data-q="bases">Comparar bases</button><button class="ghost-btn ai-q" data-q="motoristas">Produtividade de motoristas</button><button class="ghost-btn ai-q" data-q="ocorrencias">Resumir ocorrências</button></div><textarea id="aiQuestion" rows="4" placeholder="Ex.: Qual base precisa de mais atenção?"></textarea><button class="primary-btn" id="aiAsk">Analisar dados</button></div><div class="card"><h3>Resultado</h3><div id="aiAnswer" class="ai-answer">Escolha uma análise ou faça uma pergunta.</div></div></div>`}
function reports(){let total=state.orders.length,ent=state.orders.filter(x=>x.status==='Entregue').length,occ=state.orders.filter(x=>x.status==='Ocorrência').length;return `<div class="grid kpis">${kpi('Taxa de entrega',total?Math.round(ent/total*100)+'%':'0%','Volumes concluídos')}${kpi('Insucesso',total?Math.round(occ/total*100)+'%':'0%','Ocorrências abertas')}${kpi('Carga processada',total,'Waybills')}${kpi('Dentro do SLA',state.orders.filter(x=>slaText(x)!=='Atrasado').length,'Volumes')}</div><div class="card" style="margin-top:18px"><div class="toolbar"><h3>Exportação operacional</h3><button class="primary-btn" onclick="exportCSV()">Baixar CSV</button></div>${table(state.orders,false)}</div>`}

const pages={dashboard,recebimento:()=>listPage('Recebimento','Volumes aguardando triagem'),triagem:()=>listPage('Triagem','Volumes em separação'),despacho:()=>listPage('Despacho','Selecione ••• para avançar o status'),rota:()=>listPage('Em rota','Acompanhamento dos motoristas'),entregues:()=>listPage('Entregue','Histórico de baixas'),ocorrencias:()=>listPage('Ocorrência','Volumes que precisam de tratativa'),devolucoes:()=>listPage('Devolução','Retorno ao remetente'),sla:slaPage,motoristas:driversPage,bases:basesPage,despesas:expensesPage,usuarios:usersPage,ia:iaPage,relatorios:reports};

function render(p='dashboard'){
 let item=navItems.find(x=>x[0]===p)||navItems[0];$('#pageTitle').textContent=item[2];$('#pageSubtitle').textContent=item[3];$('#content').innerHTML=pages[item[0]]();$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===item[0]));history.replaceState(null,'','#'+item[0]);
 let s=$('#search');if(s)s.oninput=e=>{let q=e.target.value.toLowerCase();$$('tbody tr').forEach(tr=>tr.style.display=tr.innerText.toLowerCase().includes(q)?'':'none')};
 if(item[0]==='sla'){renderSlaResults();$('#slaApply').onclick=renderSlaResults;$('#slaClear').onclick=()=>{let st=new Date();st.setDate(st.getDate()-7);$('#slaStart').value=st.toISOString().slice(0,10);$('#slaEnd').value=todayISO();$('#slaDriver').value='';$('#slaBase').value='';$('#slaLocal').value='';renderSlaResults()}}
 if(item[0]==='motoristas')$('#addDriver').onclick=()=>openDriver();
 if(item[0]==='bases')$('#addBase').onclick=()=>openBase();
 if(item[0]==='despesas')$('#addExpense').onclick=()=>{fillDialogOptions();$('#expenseForm').reset();$('#expenseForm [name=data]').value=todayISO();$('#expenseDialog').showModal()};
 if(item[0]==='usuarios')$('#addUser').onclick=()=>{fillDialogOptions();$('#userForm').reset();$('#userDialog').showModal()};
 if(item[0]==='ia')bindAI();
}

$('#nav').innerHTML=navItems.map(x=>`<button class="nav-btn" data-page="${x[0]}"><span>${x[1]}</span><div><strong>${x[2]}</strong><small>${x[3]}</small></div></button>`).join('');
$('#nav').onclick=e=>{let b=e.target.closest('.nav-btn');if(b){render(b.dataset.page);closeMenu()}};

window.openActions=id=>{let o=state.orders.find(x=>x.waybill===id);if(!o)return;let options=o.status==='Recebido no DS'?['Triagem']:o.status==='Triagem'?['Despachado']:o.status==='Despachado'?['Em rota']:o.status==='Em rota'?['Entregue','Ocorrência']:o.status==='Ocorrência'?['Em rota','Devolução']:[];let assign=o.status==='Triagem'||o.status==='Despachado';let extra=assign?'\nM. Atribuir motorista':'';let choice=prompt(`${id} — ${o.status}\nPróximo status:\n${options.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n0. Registrar ocorrência${extra}`);if(choice==='0'){openOcc(id);return}if(choice?.toLowerCase()==='m'&&assign){let names=state.drivers.filter(d=>d.status==='Ativo').map(d=>d.nome);let n=prompt('Motoristas:\n'+names.map((x,i)=>`${i+1}. ${x}`).join('\n'));let name=names[Number(n)-1];if(name){o.entregador=name;o.atualizacao=now();save();toast('Motorista atribuído');render(location.hash.slice(1)||'despacho')}return}let next=options[Number(choice)-1];if(next){o.status=next;o.ultimo=next==='Entregue'?'Entregue':next;o.atualizacao=now();save();toast(`${id}: ${next}`);render(location.hash.slice(1)||'dashboard')}};
function openOcc(id){let o=state.orders.find(x=>x.waybill===id);$('#occForm [name=waybill]').value=id;$('#occWb').textContent=id+' • '+o.destinatario;$('#occDialog').showModal()} window.openOcc=openOcc;
$('#occForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),o=state.orders.find(x=>x.waybill===f.get('waybill'));o.status='Ocorrência';o.ocorrencia=f.get('tipo');o.ultimo='Tentativa sem sucesso';o.atualizacao=now();save();$('#occDialog').close();toast('Ocorrência registrada');render('ocorrencias')};

$('#newBtn').onclick=()=>{fillDialogOptions();$('#wbForm').reset();$('#wbForm [name=prazo]').value=todayISO();$('#wbDialog').showModal()};
$$('.close').forEach(b=>b.onclick=()=>$('#wbDialog').close());$$('.close-occ').forEach(b=>b.onclick=()=>$('#occDialog').close());$$('.close-driver').forEach(b=>b.onclick=()=>$('#driverDialog').close());$$('.close-expense').forEach(b=>b.onclick=()=>$('#expenseDialog').close());$$('.close-user').forEach(b=>b.onclick=()=>$('#userDialog').close());$$('.close-base').forEach(b=>b.onclick=()=>$('#baseDialog').close());
$('#wbForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),id=f.get('waybill').trim();if(state.orders.some(x=>x.waybill===id)){toast('Waybill já cadastrado');return}state.orders.unshift({waybill:id,referencia:f.get('referencia'),cliente:f.get('cliente'),destinatario:f.get('destinatario'),telefone:f.get('telefone'),endereco:f.get('endereco'),cidade:f.get('cidade'),localidade:f.get('localidade'),base:f.get('base'),prazo:f.get('prazo'),status:'Recebido no DS',volumes:Number(f.get('volumes')||1),entregador:'',ultimo:'Recebido no DS',atualizacao:now(),ocorrencia:''});save();e.target.reset();$('#wbDialog').close();toast('Waybill recebido no DS');render('recebimento')};

function openDriver(id=''){fillDialogOptions();let form=$('#driverForm');form.reset();form.elements.id.value=id;if(id){let d=state.drivers.find(x=>x.id===id);Object.keys(d).forEach(k=>{if(form.elements[k])form.elements[k].value=d[k]??''})}$('#driverDialog').showModal()} window.editDriver=openDriver;
$('#driverForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),id=f.get('id'),data={id:id||uid(),nome:f.get('nome'),telefone:f.get('telefone'),nascimento:f.get('nascimento'),rota:f.get('rota'),valorPacote:Number(f.get('valorPacote')||0),base:f.get('base'),banco:f.get('banco'),agencia:f.get('agencia'),conta:f.get('conta'),pix:f.get('pix'),status:f.get('status'),obs:f.get('obs')};if(id){let i=state.drivers.findIndex(x=>x.id===id);state.drivers[i]=data}else state.drivers.push(data);save();$('#driverDialog').close();toast('Motorista salvo');render('motoristas')};

function openBase(id=''){let form=$('#baseForm');form.reset();form.elements.id.value=id;if(id){let b=state.bases.find(x=>x.id===id);Object.keys(b).forEach(k=>{if(form.elements[k])form.elements[k].value=b[k]??''})}$('#baseDialog').showModal()} window.editBase=openBase;
$('#baseForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),id=f.get('id'),data={id:id||uid(),nome:f.get('nome'),localidade:f.get('localidade'),status:f.get('status')};if(id){let i=state.bases.findIndex(x=>x.id===id),old=state.bases[i].nome;state.bases[i]=data;state.orders.forEach(o=>{if(o.base===old)o.base=data.nome});state.drivers.forEach(d=>{if(d.base===old)d.base=data.nome});state.expenses.forEach(x=>{if(x.base===old)x.base=data.nome})}else state.bases.push(data);save();$('#baseDialog').close();toast('Base salva');render('bases')};

$('#expenseForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);state.expenses.unshift({id:uid(),descricao:f.get('descricao'),valor:Number(f.get('valor')||0),data:f.get('data'),pagamento:f.get('pagamento'),categoria:f.get('categoria'),base:f.get('base'),responsavel:f.get('responsavel'),obs:f.get('obs')});save();$('#expenseDialog').close();toast('Despesa registrada');render('despesas')};
window.deleteExpense=id=>{if(confirm('Excluir esta despesa?')){state.expenses=state.expenses.filter(x=>x.id!==id);save();render('despesas')}};
$('#userForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);state.users.push({id:uid(),nome:f.get('nome'),email:f.get('email'),perfil:f.get('perfil'),base:f.get('base'),status:f.get('status')});save();$('#userDialog').close();toast('Usuário cadastrado');render('usuarios')};

function isBirthdayToday(d){if(!d.nascimento)return false;let n=new Date(d.nascimento+'T12:00'),t=new Date();return n.getDate()===t.getDate()&&n.getMonth()===t.getMonth()}
window.birthdayMessage=id=>{let d=state.drivers.find(x=>x.id===id);let msg=`Feliz aniversário, ${d.nome.split(' ')[0]}! Desejamos um excelente dia, muita saúde, felicidade e sucesso. 🎉`;navigator.clipboard?.writeText(msg);alert(msg+'\n\nMensagem copiada. O envio automático por WhatsApp será conectado na etapa de backend/API.')};

function bindAI(){
 $$('.ai-q').forEach(b=>b.onclick=()=>{$('#aiQuestion').value=b.dataset.q;runAI(b.dataset.q)});$('#aiAsk').onclick=()=>runAI($('#aiQuestion').value)
}
function runAI(q){q=(q||'').toLowerCase();let ans='';if(q.includes('sla')){let late=state.orders.filter(o=>slaText(o)==='Atrasado');ans=`Há ${late.length} volume(s) com SLA vencido em ${state.orders.length} registros. ${late.length?'Priorize '+[...new Set(late.map(x=>x.base))].join(', ')+'.':'Não há atraso no conjunto atual.'}`}
 else if(q.includes('base')){let stats=state.bases.map(b=>{let a=state.orders.filter(o=>o.base===b.nome),late=a.filter(o=>slaText(o)==='Atrasado').length;return {b:b.nome,t:a.length,l:late}}).sort((a,b)=>b.l-a.l);ans=stats.map(x=>`${x.b}: ${x.t} pacote(s), ${x.l} atrasado(s)`).join('\n')}
 else if(q.includes('motorista')||q.includes('produt')){let names=state.drivers.map(d=>({n:d.nome,e:state.orders.filter(o=>o.entregador===d.nome&&o.status==='Entregue').length,r:state.orders.filter(o=>o.entregador===d.nome).length})).sort((a,b)=>b.e-a.e);ans=names.map(x=>`${x.n}: ${x.e} entregue(s) de ${x.r} atribuído(s)`).join('\n')}
 else if(q.includes('ocorr')){let oc=state.orders.filter(o=>o.status==='Ocorrência');let types={};oc.forEach(o=>types[o.ocorrencia||'Sem tipo']=(types[o.ocorrencia||'Sem tipo']||0)+1);ans=`Ocorrências abertas: ${oc.length}.\n`+Object.entries(types).map(([k,v])=>`${k}: ${v}`).join('\n')}
 else {let late=state.orders.filter(o=>slaText(o)==='Atrasado').length,occ=state.orders.filter(o=>o.status==='Ocorrência').length;ans=`Resumo operacional: ${state.orders.length} Waybill(s), ${late} atrasado(s), ${occ} ocorrência(s) e ${state.drivers.filter(d=>d.status==='Ativo').length} motorista(s) ativo(s). Para uma análise mais específica, mencione SLA, base, motorista ou ocorrências.`}
 $('#aiAnswer').textContent=ans;
}

$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>importCSV(r.result);r.readAsText(file,'UTF-8')};
function importCSV(text){let lines=text.trim().split(/\r?\n/);if(lines.length<2){toast('CSV vazio');return}let sep=lines[0].includes(';')?';':',';let h=lines[0].split(sep).map(x=>x.trim().toLowerCase());let added=0;for(let line of lines.slice(1)){let v=line.split(sep).map(x=>x.trim()),g=n=>v[h.indexOf(n)]||'';let id=g('waybill');if(!id||state.orders.some(x=>x.waybill===id))continue;state.orders.push({waybill:id,referencia:g('referencia'),cliente:g('cliente'),destinatario:g('destinatario'),telefone:g('telefone'),endereco:g('endereco'),cidade:g('cidade'),localidade:g('localidade')||g('cidade'),base:g('base')||state.bases[0]?.nome||'Base 1',prazo:g('prazo')||todayISO(),status:'Recebido no DS',volumes:Number(g('volumes')||1),entregador:g('motorista')||'',ultimo:'Importado / Recebido no DS',atualizacao:now(),ocorrencia:''});added++}save();toast(`${added} Waybill(s) importados`);render('recebimento')}
window.exportCSV=()=>{let h=['waybill','referencia','cliente','destinatario','telefone','endereco','cidade','localidade','base','prazo','status','volumes','entregador','ultimo','atualizacao','ocorrencia'];let q=x=>'"'+String(x??'').replaceAll('"','""')+'"';let csv='\ufeff'+h.join(';')+'\n'+state.orders.map(o=>h.map(k=>q(o[k])).join(';')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='operacao-last-mile.csv';a.click();URL.revokeObjectURL(a.href)};
function closeMenu(){$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')}$('#menuBtn').onclick=()=>{$('#sidebar').classList.toggle('open');$('#overlay').classList.toggle('show')};$('#overlay').onclick=closeMenu;window.onhashchange=()=>render(location.hash.slice(1)||'dashboard');fillDialogOptions();render(location.hash.slice(1)||'dashboard');
