const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const navItems=[['dashboard','▦','Dashboard','Visão geral da operação DS'],['recebimento','▥','Recebimento DS','Entrada e conferência de carga'],['triagem','⌗','Triagem','Separação e preparação'],['despacho','⇄','Despacho','Distribuição para entregadores'],['rota','⌁','Em rota','Acompanhamento das saídas'],['entregues','✓','Entregues','Baixas e comprovantes'],['ocorrencias','!','Ocorrências','Insucessos e tratativas'],['devolucoes','↩','Devoluções','Retorno de volumes'],['relatorios','▤','Relatórios','SLA e produtividade']];
const now=()=>new Date().toLocaleString('pt-BR');
const demo={orders:[
{waybill:'WB260824001',referencia:'PED-90831',cliente:'Loja Alpha',destinatario:'Carlos Silva',telefone:'71999990001',endereco:'Rua A, 120',cidade:'Salvador',prazo:'2026-08-24',status:'Em rota',volumes:1,entregador:'Rafael Santos',ultimo:'Saiu para entrega',atualizacao:'24/08/2026 18:42',ocorrencia:''},
{waybill:'WB260824002',referencia:'PED-90832',cliente:'Marketplace Beta',destinatario:'Ana Souza',telefone:'71999990002',endereco:'Av. Central, 45',cidade:'Candeias',prazo:'2026-08-25',status:'Recebido no DS',volumes:2,entregador:'',ultimo:'Recebido no DS',atualizacao:'24/08/2026 17:10',ocorrencia:''},
{waybill:'WB260824003',referencia:'PED-90833',cliente:'Loja Alpha',destinatario:'João Santos',telefone:'71999990003',endereco:'Rua das Flores, 9',cidade:'Simões Filho',prazo:'2026-08-24',status:'Entregue',volumes:1,entregador:'Lucas Rocha',ultimo:'Entregue',atualizacao:'24/08/2026 16:25',ocorrencia:''},
{waybill:'WB260824004',referencia:'PED-90834',cliente:'Seller Gamma',destinatario:'Marcos Lima',telefone:'71999990004',endereco:'Rua B, 77',cidade:'Salvador',prazo:'2026-08-23',status:'Ocorrência',volumes:1,entregador:'Diego Lima',ultimo:'Tentativa sem sucesso',atualizacao:'24/08/2026 15:18',ocorrencia:'Destinatário ausente'},
{waybill:'WB260824005',referencia:'PED-90835',cliente:'Marketplace Beta',destinatario:'Paula Reis',telefone:'71999990005',endereco:'Praça Norte, 20',cidade:'Candeias',prazo:'2026-08-25',status:'Triagem',volumes:3,entregador:'',ultimo:'Em triagem',atualizacao:'24/08/2026 18:05',ocorrencia:''}
],drivers:['Rafael Santos','Diego Lima','Lucas Rocha','André Costa']};
const KEY='last-mile-ds-v4'; let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(demo); const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function badge(s){let c=s==='Entregue'?'green':s==='Ocorrência'||s==='Devolução'?'red':s==='Em rota'?'blue':s==='Triagem'||s==='Despachado'?'orange':'';return `<span class="badge ${c}">${s}</span>`}
function sla(o){const d=new Date(o.prazo+'T23:59:59'), today=new Date(); if(o.status==='Entregue')return '<span class="sla ok">Concluído</span>'; const days=Math.ceil((d-today)/86400000);return days<0?'<span class="sla late">Atrasado</span>':days===0?'<span class="sla warn">Vence hoje</span>':`<span class="sla ok">${days}d restante</span>`}
function kpi(t,v,s,c=''){return `<div class="card kpi ${c}"><span>${t}</span><strong>${v}</strong><small>${s}</small></div>`}
function table(rows,actions=true){return `<div class="table-wrap"><table class="table"><thead><tr><th>Waybill</th><th>Referência</th><th>Cliente</th><th>Destinatário</th><th>Cidade</th><th>Prazo</th><th>SLA</th><th>Status</th><th>Última atualização</th>${actions?'<th>Ações</th>':''}</tr></thead><tbody>${rows.map(o=>`<tr><td><strong>${o.waybill}</strong></td><td>${o.referencia||'-'}</td><td>${o.cliente}</td><td>${o.destinatario}</td><td>${o.cidade}</td><td>${new Date(o.prazo+'T12:00').toLocaleDateString('pt-BR')}</td><td>${sla(o)}</td><td>${badge(o.status)}</td><td><small>${o.ultimo}<br>${o.atualizacao}</small></td>${actions?`<td><button class="row-btn" onclick="openActions('${o.waybill}')">•••</button></td>`:''}</tr>`).join('')||'<tr><td colspan="10" class="empty">Nenhum volume nesta etapa.</td></tr>'}</tbody></table></div>`}
function dashboard(){let n=state.orders.length,e=state.orders.filter(x=>x.status==='Entregue').length,r=state.orders.filter(x=>x.status==='Em rota').length,oc=state.orders.filter(x=>x.status==='Ocorrência').length,late=state.orders.filter(x=>slaText(x)==='Atrasado').length;return `<div class="grid kpis">${kpi('Carga total',n,'Waybills na operação')}${kpi('Em rota',r,'Saídas ativas')}${kpi('Entregues',e,'Baixas concluídas')}${kpi('Ocorrências',oc,'Requer tratativa','warn')}${kpi('SLA vencido',late,'Volumes atrasados','danger')}</div><div class="grid section-grid"><div class="card"><h3>Fluxo operacional</h3><div class="flow">${['Recebido no DS','Triagem','Despachado','Em rota','Entregue'].map(s=>`<div><b>${state.orders.filter(x=>x.status===s).length}</b><span>${s}</span></div>`).join('')}</div></div><div class="card"><h3>Atenção operacional</h3><div class="mini-list">${state.orders.filter(x=>x.status==='Ocorrência'||slaText(x)==='Atrasado').map(x=>`<div class="mini-item"><div><strong>${x.waybill}</strong><span>${x.ocorrencia||slaText(x)} • ${x.cidade}</span></div>${badge(x.status)}</div>`).join('')||'<div class="empty">Sem pendências críticas.</div>'}</div></div></div>`}
function slaText(o){const d=new Date(o.prazo+'T23:59:59');if(o.status==='Entregue')return'Concluído';return d<new Date()?'Atrasado':d.toDateString()===new Date().toDateString()?'Vence hoje':'No prazo'}
function listPage(status,title,help){let rows=status==='Recebimento'?state.orders.filter(x=>x.status==='Recebido no DS'):status==='Triagem'?state.orders.filter(x=>x.status==='Triagem'):status==='Despacho'?state.orders.filter(x=>['Despachado','Recebido no DS','Triagem'].includes(x.status)):status==='Em rota'?state.orders.filter(x=>x.status==='Em rota'):status==='Entregue'?state.orders.filter(x=>x.status==='Entregue'):status==='Ocorrência'?state.orders.filter(x=>x.status==='Ocorrência'):state.orders.filter(x=>x.status==='Devolução');return `<div class="card"><div class="toolbar"><input class="search" id="search" placeholder="Buscar Waybill, referência, cliente ou destinatário"><span class="toolbar-note">${help}</span></div>${table(rows)}</div>`}
function reports(){let total=state.orders.length,ent=state.orders.filter(x=>x.status==='Entregue').length,occ=state.orders.filter(x=>x.status==='Ocorrência').length;return `<div class="grid kpis">${kpi('Taxa de entrega',total?Math.round(ent/total*100)+'%':'0%','Volumes concluídos')}${kpi('Insucesso',total?Math.round(occ/total*100)+'%':'0%','Ocorrências abertas')}${kpi('Carga processada',total,'Waybills')}${kpi('Dentro do SLA',state.orders.filter(x=>slaText(x)!=='Atrasado').length,'Volumes')}</div><div class="card" style="margin-top:18px"><div class="toolbar"><h3>Exportação operacional</h3><button class="primary-btn" onclick="exportCSV()">Baixar CSV</button></div>${table(state.orders,false)}</div>`}
const pages={dashboard,recebimento:()=>listPage('Recebimento','Recebimento','Volumes aguardando triagem'),triagem:()=>listPage('Triagem','Triagem','Volumes em separação'),despacho:()=>listPage('Despacho','Despacho','Selecione ••• para avançar o status'),rota:()=>listPage('Em rota','Em rota','Acompanhamento de entregadores'),entregues:()=>listPage('Entregue','Entregues','Histórico de baixas'),ocorrencias:()=>listPage('Ocorrência','Ocorrências','Volumes que precisam de tratativa'),devolucoes:()=>listPage('Devolução','Devoluções','Retorno ao remetente'),relatorios:reports};
function render(p='dashboard'){let item=navItems.find(x=>x[0]===p)||navItems[0];$('#pageTitle').textContent=item[2];$('#pageSubtitle').textContent=item[3];$('#content').innerHTML=pages[item[0]]();$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===item[0]));history.replaceState(null,'','#'+item[0]);let s=$('#search');if(s)s.oninput=e=>{let q=e.target.value.toLowerCase();$$('tbody tr').forEach(tr=>tr.style.display=tr.innerText.toLowerCase().includes(q)?'':'none')}}
$('#nav').innerHTML=navItems.map(x=>`<button class="nav-btn" data-page="${x[0]}"><span>${x[1]}</span><div><strong>${x[2]}</strong><small>${x[3]}</small></div></button>`).join('');$('#nav').onclick=e=>{let b=e.target.closest('.nav-btn');if(b){render(b.dataset.page);closeMenu()}};
window.openActions=id=>{let o=state.orders.find(x=>x.waybill===id);if(!o)return;let options=o.status==='Recebido no DS'?['Triagem']:o.status==='Triagem'?['Despachado']:o.status==='Despachado'?['Em rota']:o.status==='Em rota'?['Entregue','Ocorrência']:o.status==='Ocorrência'?['Em rota','Devolução']:o.status==='Devolução'?[]:[];let choice=prompt(`${id} — ${o.status}\nPróximo status:\n${options.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n0. Registrar ocorrência`);if(choice==='0'){openOcc(id);return}let next=options[Number(choice)-1];if(next){o.status=next;o.ultimo=next==='Entregue'?'Entregue':next;o.atualizacao=now();save();toast(`${id}: ${next}`);render(location.hash.slice(1)||'dashboard')}};
function openOcc(id){let o=state.orders.find(x=>x.waybill===id);$('#occForm [name=waybill]').value=id;$('#occWb').textContent=id+' • '+o.destinatario;$('#occDialog').showModal()} window.openOcc=openOcc;
$('#occForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),o=state.orders.find(x=>x.waybill===f.get('waybill'));o.status='Ocorrência';o.ocorrencia=f.get('tipo');o.ultimo='Tentativa sem sucesso';o.atualizacao=now();save();$('#occDialog').close();toast('Ocorrência registrada');render('ocorrencias')};
$('#newBtn').onclick=()=>$('#wbDialog').showModal();$$('.close').forEach(b=>b.onclick=()=>$('#wbDialog').close());$$('.close-occ').forEach(b=>b.onclick=()=>$('#occDialog').close());
$('#wbForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),id=f.get('waybill').trim();if(state.orders.some(x=>x.waybill===id)){toast('Waybill já cadastrado');return}state.orders.unshift({waybill:id,referencia:f.get('referencia'),cliente:f.get('cliente'),destinatario:f.get('destinatario'),telefone:f.get('telefone'),endereco:f.get('endereco'),cidade:f.get('cidade'),prazo:f.get('prazo'),status:'Recebido no DS',volumes:Number(f.get('volumes')||1),entregador:'',ultimo:'Recebido no DS',atualizacao:now(),ocorrencia:''});save();e.target.reset();$('#wbDialog').close();toast('Waybill recebido no DS');render('recebimento')};
$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>importCSV(r.result);r.readAsText(file,'UTF-8')};
function importCSV(text){let lines=text.trim().split(/\r?\n/);if(lines.length<2){toast('CSV vazio');return}let sep=lines[0].includes(';')?';':',';let h=lines[0].split(sep).map(x=>x.trim().toLowerCase());let added=0;for(let line of lines.slice(1)){let v=line.split(sep).map(x=>x.trim()),g=n=>v[h.indexOf(n)]||'';let id=g('waybill');if(!id||state.orders.some(x=>x.waybill===id))continue;state.orders.push({waybill:id,referencia:g('referencia'),cliente:g('cliente'),destinatario:g('destinatario'),telefone:g('telefone'),endereco:g('endereco'),cidade:g('cidade'),prazo:g('prazo')||new Date().toISOString().slice(0,10),status:'Recebido no DS',volumes:Number(g('volumes')||1),entregador:'',ultimo:'Importado / Recebido no DS',atualizacao:now(),ocorrencia:''});added++}save();toast(`${added} Waybill(s) importados`);render('recebimento')}
window.exportCSV=()=>{let h=['waybill','referencia','cliente','destinatario','telefone','endereco','cidade','prazo','status','volumes','entregador','ultimo','atualizacao','ocorrencia'];let esc=x=>'"'+String(x??'').replaceAll('"','""')+'"';let csv='\ufeff'+h.join(';')+'\n'+state.orders.map(o=>h.map(k=>esc(o[k])).join(';')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='operacao-last-mile.csv';a.click();URL.revokeObjectURL(a.href)};
function closeMenu(){$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')}$('#menuBtn').onclick=()=>{$('#sidebar').classList.toggle('open');$('#overlay').classList.toggle('show')};$('#overlay').onclick=closeMenu;window.onhashchange=()=>render(location.hash.slice(1)||'dashboard');render(location.hash.slice(1)||'dashboard');
